# list recipes
help:
    just --list

# lint the code
lint:
	pnpm lint

# dev server
dev:
  pnpm dev

# build the app
build:
  pnpm build

test:
  pnpm test

# Lint and then test targets (like CI does)
ci: lint test
