# list recipes
help:
    just --list

# lint the code
lint:
	cargo clippy --all-targets --all-features -- -D warnings

# dev server
dev:
  cargo run

# build the app
build:
  cargo build --release

test:
  cargo test

# Lint and then test targets (like CI does)
ci: lint test build

# build the app with podmand
image:
  podman build . -t iancleary.me/rust/app

# Run the docker Image
run:
  podman run iancleary.me/rust/app
