# list recipes
help:
    just --list

# lint the code
lint:
	pdm run scripts/lint.sh

# format the code
format:
	pdm run ruff --fix ./
	pdm run black ./

# Test app with pytest outside of docker (with fresh data/test.db from tests/conftest.py)
test:
	pdm run pytest -vv tests

pre-commit:
	pdm run pre-commit run --all-files

# Format and then run lint and test targets (like CI does)
ci: format lint test pre-commit
